# Generated by Django 2.2.5 on 2019-09-02 22:32

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='whatever')),
                ('description', models.TextField()),
                ('directed_by', models.CharField(max_length=200)),
                ('written_by', models.CharField(max_length=200)),
                ('in_theaters', models.DateField()),
                ('runtime', models.CharField(max_length=200)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Genre')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Rating')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Studio')),
            ],
        ),
    ]
